spring:
  application:
    name: my-application

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
        enable_lazy_load_no_trans: ${SPRING_JPA_PROPERTIES_HIBERNATE_ENABLE_LAZY_LOAD_NO_TRANS}

  mail:
    host: ${SPRING_MAIL_HOST}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: ${SPRING_MAIL_PORT}
    properties:
      mail:
        transport:
          protocol: ${SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL}
        smtp:
          port: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_PORT}
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
            required: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}
  app:
    jwtAccessSecret: ${SPRING_APP_JWT_ACCESS_SECRET}
    jwtRefreshSecret: ${SPRING_APP_JWT_REFRESH_SECRET}
    jwtAccessExpirationMs: ${SPRING_APP_JWT_ACCESS_EXPIRATION_MS}
    jwtRefreshExpirationMs: ${SPRING_APP_JWT_REFRESH_EXPIRATION_MS}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTH_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}



cloudinary:
  url: ${CLOUDINARY_URL}

api:
  prefix: ${API_PREFIX}

app:
  upload-dir: uploads